---
 - hosts: testserver
   user: root
   tasks: 
        - name: Install apache
          yum:
            name: httpd
            state: present
        - name: start daemon
          service: 
            name: httpd 
            state: started
            enabled: yes

